<?php
	//include all DAO files
	require_once('class/sql/Connection.class.php');
	require_once('class/sql/ConnectionFactory.class.php');
	require_once('class/sql/ConnectionProperty.class.php');
	require_once('class/sql/QueryExecutor.class.php');
	require_once('class/sql/Transaction.class.php');
	require_once('class/sql/SqlQuery.class.php');
	require_once('class/core/ArrayList.class.php');
	require_once('class/dao/DAOFactory.class.php');
 	
	require_once('class/dao/AlunoDAO.class.php');
	require_once('class/dto/Aluno.class.php');
	require_once('class/mysql/AlunoMySqlDAO.class.php');
	require_once('class/mysql/ext/AlunoMySqlExtDAO.class.php');
	require_once('class/dao/AlunoDisciplinaDAO.class.php');
	require_once('class/dto/AlunoDisciplina.class.php');
	require_once('class/mysql/AlunoDisciplinaMySqlDAO.class.php');
	require_once('class/mysql/ext/AlunoDisciplinaMySqlExtDAO.class.php');
	require_once('class/dao/AulaDAO.class.php');
	require_once('class/dto/Aula.class.php');
	require_once('class/mysql/AulaMySqlDAO.class.php');
	require_once('class/mysql/ext/AulaMySqlExtDAO.class.php');
	require_once('class/dao/CursoDAO.class.php');
	require_once('class/dto/Curso.class.php');
	require_once('class/mysql/CursoMySqlDAO.class.php');
	require_once('class/mysql/ext/CursoMySqlExtDAO.class.php');
	require_once('class/dao/DisciplinaDAO.class.php');
	require_once('class/dto/Disciplina.class.php');
	require_once('class/mysql/DisciplinaMySqlDAO.class.php');
	require_once('class/mysql/ext/DisciplinaMySqlExtDAO.class.php');
	require_once('class/dao/ProfessorDAO.class.php');
	require_once('class/dto/Professor.class.php');
	require_once('class/mysql/ProfessorMySqlDAO.class.php');
	require_once('class/mysql/ext/ProfessorMySqlExtDAO.class.php');
	require_once('class/dao/DisciplinaCursoDAO.class.php');
	require_once('class/dto/DisciplinaCurso.class.php');
	require_once('class/mysql/DisciplinaCursoMySqlDAO.class.php');
	require_once('class/mysql/ext/DisciplinaCursoMySqlExtDAO.class.php');
?>